$HYPER_KEY = SUPER ALT CTRL

bind = SUPER SHIFT, V, exec, qs -c noctalia-shell ipc call launcher clipboard
bind = SUPER, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = SUPER, space, exec, qs -c noctalia-shell ipc call launcher toggle

# App selectors
bind = $HYPER_KEY, A, exec, ~/.local/bin/os-launch-or-focus zen "uwsm-app -- zen-browser"
bind = $HYPER_KEY, S, exec, ~/.local/bin/os-launch-or-focus steam "uwsm-app -- steam"
bind = $HYPER_KEY, X, exec, ~/.local/bin/os-launch-or-focus wezterm "uwsm-app -- wezterm"
bind = $HYPER_KEY, C, exec, ~/.local/bin/os-launch-or-focus claude "uwsm-app -- claude-desktop"
bind = $HYPER_KEY, E, exec, ~/.local/bin/os-launch-or-focus telegram "uwsm-app -- telegram-desktop"
bind = $HYPER_KEY, O, exec, ~/.local/bin/os-launch-or-focus obsidian "uwsm-app -- obsidian"
bind = $HYPER_KEY, T, exec, kitty

# Apps
bind = SUPER_L, space, exec, rofi -show drun

#####
# Window controls
# Maximize
bind = $HYPER_KEY, Return, resizeactive, exact 2540 1380
bind = $HYPER_KEY, Return, centerwindow
# Center
bind = $HYPER_KEY, slash, centerwindow
# Right half
bind = $HYPER_KEY, period, resizeactive, exact 1265 1380
bind = $HYPER_KEY, period, moveactive, exact 1285 48
# Left half  
bind = $HYPER_KEY, comma, resizeactive, exact 1265 1380 # 1420 height original
bind = $HYPER_KEY, comma, moveactive, exact 11 48
# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

######
# MEDIA CONTROL #
#####

# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous

# Lock screen
bindl = , code:599, exec, quickshell -c noctalia-shell ipc call lockScreen lock
