general {
    lock_cmd = quickshell -c noctalia-shell ipc call lockScreen lock
}

listener {
    timeout = 300
    on-timeout = quickshell -c noctalia-shell ipc call lockScreen lock
}

listener {
    timeout = 305
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
