# Copy / Paste (Universal - works everywhere)
bindd = SUPER, C, Universal copy, sendshortcut, CTRL, Insert,
bind = SUPER, V, sendshortcut, CTRL SHIFT, V, activewindow
bindd = SUPER, X, Universal cut, sendshortcut, CTRL, X,
#bindd = SUPER CTRL, V, Clipboard manager, exec, omarchy-launch-walker -m clipboard

# Other macOS-like shortcuts
bindd = SUPER, Z, Undo, sendshortcut, CTRL, U,
bindd = SUPER, A, Select all, sendshortcut, CTRL, A,
bindd = SUPER, S, Save, sendshortcut, CTRL, S,
bindd = SUPER, F, Find, sendshortcut, CTRL, F,
bindd = SUPER, G, Find next, sendshortcut, CTRL, G,
bindd = SUPER, R, Refresh, sendshortcut, CTRL, R,
bindd = SUPER, T, New tab, sendshortcut, CTRL, T,
bindd = SUPER, W, Close tab, sendshortcut, CTRL, W,
bindd = SUPER, N, New window, sendshortcut, CTRL, N,
bind = SUPER, Q, killactive,

# Cursor movement and text slection
bindd = SUPER, left, Home, sendshortcut, , home,
bindd = SUPER, right, End, sendshortcut, , end,
bindd = SUPER_SHIFT, left, Home select, sendshortcut, SHIFT, home,
bindd = SUPER_SHIFT, right, End select, sendshortcut, SHIFT, end,
bindd = ALT, left, Word left, sendshortcut, CTRL, left,
bindd = ALT, right, Word right, sendshortcut, CTRL, right,
bindd = ALT_SHIFT, left, Word left select, sendshortcut, CTRL_SHIFT, left,
bindd = ALT_SHIFT, right, Word right select, sendshortcut, CTRL_SHIFT, right,
bindd = SUPER, backspace, Delete line, sendshortcut, CTRL_SHIFT, backspace,
bindd = ALT, backspace, Delete word, sendshortcut, CTRL, backspace,

