# See https://wiki.hypr.land/Configuring/Monitors/
monitor=,3840x2160@120,auto,1.5,bitdepth,10
# monitor=,3840x2160@120,auto,1,bitdepth,10
# env = GDK_DPI_SCALE,1.5
# env = QT_FONT_DPI,144
# env = XCURSOR_SIZE,36
